# ----
# Site

title: Mixin
description: Jekyll template for API documentation.
url: https://developers.mixin.one/api
baseurl: ""
permalink: pretty

# -----
# Build

timezone: Asia/Shanghai

collections:
  documentation:
    title: Documentation
    position: 1
  api:
    title: APIs
    position: 2
  app_api:
    title: APP APIs
    position: 3
  websocket:
    title: Websocket
    position: 4

exclude:
  - readme.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "documentation"
    values:
      _hide_content: true
  -
    scope:
      type: "api"
    values:
      _hide_content: true

types:
  - get
  - post

languages:
  bash: Bash
  json: JSON
  golang: Golang

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
